[package]
name = "autokernel"
version = "0.1.0"
edition = "2021"
authors = ["oddlama <oddlama@oddlama.org>", "clotodex <clotodex@online.de>"]

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
dotenv = "0.15.0"
libc = "*"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.83", features = ["unbounded_depth"] }
toml = "0.5.9"
libloading = "0.7.3"
thiserror = "1.0.32"
anyhow = "1.0.62"
colored = "2.0.0"
