[package]
name = "autokernel"
version = "0.1.0"
edition = "2021"
authors = ["oddlama <oddlama@oddlama.org>", "clotodex <clotodex@online.de>"]

[features]
index = ["dep:rusqlite", "dep:uuid"]

[[bin]]
name = "autokernel"

[[bin]]
name = "autokernel-index"
required-features = ["index"]

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
libc = "*"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.83", features = ["unbounded_depth"] }
libloading = "0.7.3"
thiserror = "1.0.32"
anyhow = { version = "1.0.62", features = ["backtrace"] }
colored = "2.0.0"
bitflags = "1.3.2"
rlua = "0.19.4"
itertools = "0.10.5"
strum = { version = "0.24.1", features = ["derive"] }
rusqlite = { version = "0.28.0", optional = true }
uuid = { version = "1.2.1", features = ["v4"], optional = true }
toml = "0.5.9"
tempdir = "0.3.7"

[dev-dependencies]
serial_test = "0.9.0"
