[package]
name = "autokernel"
version = "0.1.0"
edition = "2021"
authors = ["oddlama <oddlama@oddlama.org>", "clotodex <clotodex@online.de>"]

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
libc = "*"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.83", features = ["unbounded_depth"] }
libloading = "0.7.3"
thiserror = "1.0.32"
anyhow = { version = "1.0.62", features = ["backtrace"] }
colored = "2.0.0"
const_format = { version = "0.2.26"}
bitflags = "1.3.2"
indexmap = "1.9.1"
rlua = "0.19.4"
env_logger = "0.9.1"
log = "0.4.17"
serial_test = "0.9.0"
